#!/bin/bash

# HMS Deployment Script
# This script deploys the HMS application with Traefik integration

set -e

# Configuration
DOMAIN="152.53.164.124"
PROJECT_NAME="hms"
NETWORK_NAME="traefik_proxy"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to check prerequisites
check_prerequisites() {
    print_status "Checking prerequisites..."
    
    if ! command_exists docker; then
        print_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    
    if ! command_exists docker composer; then
        print_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi
    
    # Check if Traefik network exists
    if ! docker network ls | grep -q "$NETWORK_NAME"; then
        print_warning "Traefik network '$NETWORK_NAME' does not exist. Creating it..."
        docker network create "$NETWORK_NAME" || {
            print_error "Failed to create Traefik network. Please ensure Traefik is running."
            exit 1
        }
    fi
    
    print_success "Prerequisites check passed"
}

# Function to update domain in configuration files
update_domain() {
    print_status "Updating domain configuration..."
    
    # Update backend compose file
    sed -i.bak "s/your-domain.com/$DOMAIN/g" docker-compose.backend.yml
    
    # Update frontend compose file
    sed -i.bak "s/your-domain.com/$DOMAIN/g" docker-compose.frontend.yml
    
    # Update frontend environment
    sed -i.bak "s/your-domain.com/$DOMAIN/g" hms-frontend/Dockerfile.frontend
    
    print_success "Domain configuration updated"
}

# Function to prepare production configuration
prepare_production_config() {
    print_status "Preparing production configuration..."
    
    # Check if application-prod.yml exists
    if [ ! -f "src/main/resources/application-production.yml" ]; then
        print_error "application-production.yml not found in src/main/resources/"
        exit 1
    fi
    
    # Check if custom production environment file exists
    if [ -f ".env.production.custom" ]; then
        print_status "Using custom production environment file..."
        cp .env.production.custom .env.production
    else
        # Create default production environment file
        cat > .env.production << EOF
# Production Environment Variables
# This file is automatically generated by deploy.sh
# To customize, create .env.production.custom with your values

SPRING_PROFILES_ACTIVE=production
SPRING_DATASOURCE_URL=jdbc:postgresql://hms-db:5432/hms_db
SPRING_DATASOURCE_USERNAME=hms_user
SPRING_DATASOURCE_PASSWORD=hms_password
SPRING_JPA_HIBERNATE_DDL_AUTO=update
SPRING_JPA_SHOW_SQL=false
SERVER_PORT=8080
MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always

# MinIO Configuration
MINIO_ENDPOINT=http://hms-minio:9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin123
MINIO_BUCKET_NAME=hms-files

# JWT Configuration (CHANGE THESE IN PRODUCTION!)
JWT_SECRET=change-this-secret-key-change-this-secret-key
JWT_ACCESS_TTL=86400
JWT_REFRESH_TTL=604800

# SMTP Configuration (set these in your environment)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
EOF
    fi
    
    print_success "Production configuration prepared"
    print_warning "IMPORTANT: Change JWT_SECRET in production!"
    print_warning "Create .env.production.custom to override default values"
    print_warning "See env.production.example for customization options"
}

# Function to build and start backend
deploy_backend() {
    print_status "Deploying HMS Backend..."
    
    # Build and start backend services with production environment
    docker compose -f docker-compose.backend.yml --env-file .env.production -p "$PROJECT_NAME-backend" up -d --build
    
    # Wait for database to be ready
    print_status "Waiting for database to be ready..."
    sleep 10
    
}

# Function to build and start frontend
deploy_frontend() {
    print_status "Deploying HMS Frontend..."
    
    # Build and start frontend
    docker compose -f docker-compose.frontend.yml -p "$PROJECT_NAME-frontend" up -d --build
    
    # Wait for frontend to be ready
    print_status "Waiting for frontend to be ready..."
    sleep 5
    
}

# Function to show deployment status
show_status() {
    print_status "Deployment Status:"
    echo ""
    echo "Backend Services:"
    docker compose -f docker-compose.backend.yml -p "$PROJECT_NAME-backend" ps
    echo ""
    echo "Frontend Services:"
    docker compose -f docker-compose.frontend.yml -p "$PROJECT_NAME-frontend" ps
    echo ""
    print_success "HMS Application deployed successfully!"
    echo ""
    echo "Access URLs:"
    echo "  Frontend: https://$DOMAIN/hms"
    echo "  Backend API: https://$DOMAIN/hms/api"
    echo "  Health Check: https://$DOMAIN/hms/api/actuator/health"
    echo ""
    echo "Configuration:"
    echo "  Profile: production"
    echo "  Config File: application-prod.yml"
    echo "  Environment: .env.production"
    echo ""
    echo "Database (for debugging):"
    echo "  Host: localhost"
    echo "  Port: 5433"
    echo "  Database: hms_db"
    echo "  Username: hms_user"
    echo "  Password: hms_password"
    echo ""
    echo "MinIO (for file storage):"
    echo "  URL: http://localhost:9000"
    echo "  Username: minioadmin"
    echo "  Password: minioadmin123"
    echo ""
    echo "Production Notes:"
    echo "  - JWT tokens expire in 24 hours"
    echo "  - Database schema is updated automatically"
    echo "  - Logs are written to /app/logs in container"
    echo "  - Customize settings via .env.production.custom"
}

# Function to cleanup
cleanup() {
    print_status "Cleaning up temporary files..."
    rm -f docker-compose.backend.yml.bak docker-compose.frontend.yml.bak hms-frontend/Dockerfile.frontend.bak .env.production
}

# Main deployment function
main() {
    echo "=========================================="
    echo "    HMS Deployment Script"
    echo "=========================================="
    echo ""
    
    # Check if domain is provided
    if [ -n "$1" ]; then
        DOMAIN="$1"
        print_status "Using domain: $DOMAIN"
    else
        print_warning "No domain provided. Using default: $DOMAIN"
        print_warning "You can specify a domain as the first argument: ./deploy.sh your-domain.com"
    fi
    
    # Run deployment steps
    check_prerequisites
    prepare_production_config
    update_domain
    deploy_backend
    deploy_frontend
    show_status
    cleanup
    
    print_success "Deployment completed successfully!"
}

# Handle script interruption
trap cleanup EXIT

# Run main function
main "$@"
